const en = {
  availabilityOnline: "Support online", availabilityOffline: "Support offline · Leave a message", availabilityUnknown: "Checking support availability…", read: "Read", unread: "Unread", agentTyping: "Support is typing…", userTyping: "Customer is typing…",
  latest: "Go to latest messages", resetSearch: "Show all conversations", sending: "Sending…", userKeys: "Enter to send · Shift + Enter for a new line", agentKeys: "Ctrl / ⌘ + Enter to send · Enter for a new line", characterCount: "{count} / {limit} characters",
  title: "Online support", subtitle: "A little help, right here.", open: "Chat with support", close: "Close chat", online: "Customer support", demo: "Frontend demo", demoNotice: "Messages stay in this browser during the frontend demo.",
  greeting: "How can we help?", greetingBody: "Send us a message or a screenshot. Your conversation will be here when you come back.", placeholder: "Write a message…", send: "Send message", attach: "Attach image", removeImage: "Remove image", imageHint: "PNG, JPEG or WebP · up to 2 MB", imageInvalid: "Choose a PNG, JPEG or WebP image up to 2 MB.", imageLoading: "Preparing image…", imageAlt: "Attached image", you: "You", agent: "Support", sent: "Sent", newMessages: "New messages", emptyMessage: "Write a message or attach an image.", textTooLong: "Keep your message within 4,000 characters.", saveFailed: "Could not save. Your draft is still here; please try again.", storageFull: "Demo storage is full. Remove an attachment or start a new user preview.", sessionEnded: "This demo session has ended. Please enter again.", frameBlocked: "Open this page directly to use the support demo.", unavailable: "Browser storage is unavailable. Enable it and reload to try the demo.", jsRequired: "Enable JavaScript to use support.",
  desk: "Support desk", loginHeading: "Support operator sign-in", loginTitle: "Your support desk, in one place.", loginBody: "See conversations, get to know your customers, and help them move forward.", loginNotice: "Local frontend preview. Enter a display name and email to explore; no account authentication is performed.", name: "Display name", email: "Email", enter: "Enter support demo", backToSite: "Back to Fells", logout: "Leave support demo", inbox: "Inbox", all: "All conversations", openFilter: "Open", resolvedFilter: "Resolved", unreadFilter: "Unread", search: "Search customers or messages", conversations: "Conversations", customers: "Customers", waiting: "Waiting for reply", emptyInbox: "Your inbox is ready", emptyInboxBody: "Messages from the user preview appear here. You can also load sample conversations to explore the desk.", seed: "Load sample conversations", noResults: "No matching conversations", selectConversation: "Choose a conversation", selectBody: "Read the conversation and customer details, then reply here.", details: "Customer details", back: "Back to inbox", customerId: "User ID", joined: "Joined", workspaces: "Workspaces", credits: "Demo credits", language: "Language", status: "Conversation status", resolve: "Mark resolved", reopen: "Reopen conversation", resolved: "Resolved", openStatus: "Open", sample: "Sample customer", previewUser: "Preview customer", messageCount: "messages", noMessages: "No messages yet", resolvedNotice: "This conversation is resolved. Sending a message will reopen it.", deskHint: "Local preview · replies sync between tabs in this browser", privacy: "Use sample information in this demo.", loading: "Loading conversations…",
};
export type SupportCopy = typeof en;
const zh: SupportCopy = {
  availabilityOnline: "客服在线", availabilityOffline: "暂无客服在线，可先留言", availabilityUnknown: "正在确认客服状态…", read: "已读", unread: "未读", agentTyping: "客服正在输入…", userTyping: "用户正在输入…",
  latest: "查看最新消息", resetSearch: "查看全部会话", sending: "正在发送…", userKeys: "Enter 发送 · Shift + Enter 换行", agentKeys: "Ctrl / ⌘ + Enter 发送 · Enter 换行", characterCount: "{count} / {limit} 字",
  title: "在线客服", subtitle: "遇到问题，我们来帮你。", open: "联系在线客服", close: "关闭聊天", online: "客户支持", demo: "前端演示", demoNotice: "前端演示：消息仅保存在此浏览器。",
  greeting: "有什么可以帮你？", greetingBody: "发送问题或截图，随时回来查看对话。", placeholder: "输入消息…", send: "发送消息", attach: "添加图片", removeImage: "移除图片", imageHint: "PNG、JPEG 或 WebP · 最大 2 MB", imageInvalid: "请选择不超过 2 MB 的 PNG、JPEG 或 WebP 图片。", imageLoading: "正在准备图片…", imageAlt: "消息中的图片", you: "你", agent: "客服", sent: "已发送", newMessages: "新消息", emptyMessage: "请输入文字或添加图片。", textTooLong: "消息最多 4,000 字。", saveFailed: "保存失败，草稿已保留，请重试。", storageFull: "演示存储空间已满，请移除图片或重新进入用户演示。", sessionEnded: "此演示会话已结束，请重新进入。", frameBlocked: "请直接打开此页面使用客服演示。", unavailable: "浏览器存储不可用，请启用后刷新页面。", jsRequired: "请启用 JavaScript 使用在线客服。",
  desk: "客服工作台", loginHeading: "客服登录", loginTitle: "每一次对话，都在这里。", loginBody: "查看用户会话、了解客户信息，及时解答每一个问题。", loginNotice: "本地前端预览。填写显示名称和邮箱即可体验，此入口不进行真实账号认证。", name: "显示名称", email: "邮箱", enter: "进入客服演示", backToSite: "返回 Fells", logout: "退出客服演示", inbox: "收件箱", all: "全部会话", openFilter: "处理中", resolvedFilter: "已解决", unreadFilter: "未读", search: "搜索用户或消息", conversations: "会话", customers: "用户", waiting: "待回复", emptyInbox: "准备好接待用户了", emptyInboxBody: "用户演示发送的消息会显示在这里，也可以加载示例会话体验工作台。", seed: "加载示例会话", noResults: "没有匹配的会话", selectConversation: "选择一个会话", selectBody: "在这里查看对话、了解用户信息并回复。", details: "用户资料", back: "返回会话列表", customerId: "用户 ID", joined: "加入时间", workspaces: "工作空间", credits: "演示余额", language: "语言", status: "会话状态", resolve: "标记已解决", reopen: "重新打开会话", resolved: "已解决", openStatus: "处理中", sample: "示例用户", previewUser: "演示用户", messageCount: "条消息", noMessages: "暂无消息", resolvedNotice: "此会话已解决，发送新消息会重新打开。", deskHint: "本地演示 · 同一浏览器的标签页之间同步回复", privacy: "请在演示中使用示例资料。", loading: "正在加载会话…",
};
const zhHant: SupportCopy = { ...zh, availabilityOnline: "客服在線", availabilityOffline: "暫無客服在線，可先留言", availabilityUnknown: "正在確認客服狀態…", read: "已讀", unread: "未讀", agentTyping: "客服正在輸入…", userTyping: "使用者正在輸入…", latest: "查看最新訊息", resetSearch: "查看全部會話", sending: "正在傳送…", userKeys: "Enter 傳送 · Shift + Enter 換行", agentKeys: "Ctrl / ⌘ + Enter 傳送 · Enter 換行", characterCount: "{count} / {limit} 字", title: "線上客服", subtitle: "遇到問題，我們來幫你。", open: "聯絡線上客服", close: "關閉聊天", online: "客戶支援", demo: "前端示範", demoNotice: "前端示範：訊息僅保存在此瀏覽器。", greeting: "有什麼可以幫你？", greetingBody: "傳送問題或截圖，隨時回來查看對話。", placeholder: "輸入訊息…", send: "傳送訊息", attach: "加入圖片", removeImage: "移除圖片", imageHint: "PNG、JPEG 或 WebP · 最大 2 MB", imageInvalid: "請選擇不超過 2 MB 的 PNG、JPEG 或 WebP 圖片。", imageLoading: "正在準備圖片…", imageAlt: "訊息中的圖片", you: "你", agent: "客服", sent: "已傳送", newMessages: "新訊息", emptyMessage: "請輸入文字或加入圖片。", textTooLong: "訊息最多 4,000 字。", saveFailed: "儲存失敗，草稿已保留，請重試。", storageFull: "示範儲存空間已滿，請移除圖片或重新進入使用者示範。", sessionEnded: "此示範會話已結束，請重新進入。", frameBlocked: "請直接開啟此頁面使用客服示範。", unavailable: "瀏覽器儲存不可用，請啟用後重新整理頁面。", jsRequired: "請啟用 JavaScript 使用線上客服。", desk: "客服工作台", loginHeading: "客服登入", loginTitle: "每一次對話，都在這裡。", loginBody: "查看使用者會話、了解客戶資料，及時解答每一個問題。", loginNotice: "本地前端預覽。填寫顯示名稱和信箱即可體驗，此入口不進行真實帳號認證。", name: "顯示名稱", email: "信箱", enter: "進入客服示範", backToSite: "返回 Fells", logout: "退出客服示範", inbox: "收件匣", all: "全部會話", openFilter: "處理中", resolvedFilter: "已解決", unreadFilter: "未讀", search: "搜尋使用者或訊息", conversations: "會話", customers: "使用者", waiting: "待回覆", emptyInbox: "準備好接待使用者了", emptyInboxBody: "使用者示範傳送的訊息會顯示在這裡，也可以載入範例會話體驗工作台。", seed: "載入範例會話", noResults: "沒有符合的會話", selectConversation: "選擇一個會話", selectBody: "在這裡查看對話、了解使用者資料並回覆。", details: "使用者資料", back: "返回會話清單", customerId: "使用者 ID", joined: "加入時間", workspaces: "工作空間", credits: "示範餘額", language: "語言", status: "會話狀態", resolve: "標記已解決", reopen: "重新開啟會話", resolved: "已解決", openStatus: "處理中", sample: "範例使用者", previewUser: "示範使用者", messageCount: "則訊息", noMessages: "暫無訊息", resolvedNotice: "此會話已解決，傳送新訊息會重新開啟。", deskHint: "本地示範 · 同一瀏覽器的分頁之間同步回覆", privacy: "請在示範中使用範例資料。", loading: "正在載入會話…" };
const ja: SupportCopy = {
  availabilityOnline: "サポート対応中", availabilityOffline: "不在です · メッセージを残せます", availabilityUnknown: "対応状況を確認中…", read: "既読", unread: "未読", agentTyping: "サポートが入力中…", userTyping: "お客様が入力中…",
  latest: "最新のメッセージへ", resetSearch: "すべての会話を表示", sending: "送信中…", userKeys: "Enter で送信 · Shift + Enter で改行", agentKeys: "Ctrl / ⌘ + Enter で送信 · Enter で改行", characterCount: "{count} / {limit} 文字",
  title: "オンラインサポート", subtitle: "困ったときは、ここでお手伝いします。", open: "サポートに相談", close: "チャットを閉じる", online: "カスタマーサポート", demo: "フロントエンドデモ", demoNotice: "フロントエンドデモのメッセージは、このブラウザーにのみ保存されます。",
  greeting: "何かお困りですか？", greetingBody: "メッセージやスクリーンショットを送ってください。戻ってきたときも会話を確認できます。", placeholder: "メッセージを入力…", send: "メッセージを送信", attach: "画像を添付", removeImage: "画像を削除", imageHint: "PNG、JPEG、WebP · 最大 2 MB", imageInvalid: "2 MB 以下の PNG、JPEG、WebP 画像を選択してください。", imageLoading: "画像を準備中…", imageAlt: "添付画像", you: "あなた", agent: "サポート", sent: "送信済み", newMessages: "新しいメッセージ", emptyMessage: "メッセージを入力するか、画像を添付してください。", textTooLong: "メッセージは 4,000 文字以内で入力してください。", saveFailed: "保存できませんでした。下書きは残っています。もう一度お試しください。", storageFull: "デモの保存容量がいっぱいです。画像を削除するか、新しいユーザープレビューを開始してください。", sessionEnded: "このデモセッションは終了しました。もう一度入ってください。", frameBlocked: "このページを直接開いてサポートデモをご利用ください。", unavailable: "ブラウザーの保存機能を利用できません。有効にしてページを再読み込みしてください。", jsRequired: "サポートを利用するには JavaScript を有効にしてください。",
  desk: "サポート窓口", loginHeading: "サポート担当者ログイン", loginTitle: "すべての会話を、ひとつの窓口に。", loginBody: "会話やお客様の情報を確認し、問題の解決をお手伝いします。", loginNotice: "ローカルのフロントエンドプレビューです。表示名とメールアドレスで体験できます。アカウント認証は行いません。", name: "表示名", email: "メールアドレス", enter: "サポートデモに入る", backToSite: "Fells に戻る", logout: "サポートデモを終了", inbox: "受信トレイ", all: "すべての会話", openFilter: "対応中", resolvedFilter: "解決済み", unreadFilter: "未読", search: "お客様やメッセージを検索", conversations: "会話", customers: "お客様", waiting: "返信待ち", emptyInbox: "受付の準備ができました", emptyInboxBody: "ユーザープレビューからのメッセージがここに表示されます。サンプルの会話を読み込んで窓口を体験することもできます。", seed: "サンプルの会話を読み込む", noResults: "一致する会話がありません", selectConversation: "会話を選択してください", selectBody: "会話とお客様の情報を確認して、ここから返信できます。", details: "お客様の情報", back: "受信トレイに戻る", customerId: "ユーザー ID", joined: "登録日", workspaces: "ワークスペース", credits: "デモクレジット", language: "言語", status: "会話の状態", resolve: "解決済みにする", reopen: "会話を再開", resolved: "解決済み", openStatus: "対応中", sample: "サンプルのお客様", previewUser: "プレビューのお客様", messageCount: "件のメッセージ", noMessages: "まだメッセージはありません", resolvedNotice: "この会話は解決済みです。メッセージを送ると再開します。", deskHint: "ローカルプレビュー · このブラウザーのタブ間で返信を同期", privacy: "デモではサンプルの情報を使用してください。", loading: "会話を読み込み中…",
};
const ko: SupportCopy = {
  availabilityOnline: "상담원 온라인", availabilityOffline: "상담원 부재 · 메시지를 남겨 주세요", availabilityUnknown: "상담원 상태 확인 중…", read: "읽음", unread: "읽지 않음", agentTyping: "상담원이 입력 중…", userTyping: "고객이 입력 중…",
  latest: "최신 메시지 보기", resetSearch: "모든 대화 보기", sending: "전송 중…", userKeys: "Enter로 전송 · Shift + Enter로 줄 바꿈", agentKeys: "Ctrl / ⌘ + Enter로 전송 · Enter로 줄 바꿈", characterCount: "{count} / {limit}자",
  title: "온라인 고객 지원", subtitle: "도움이 필요하면 여기에서 문의하세요.", open: "고객 지원에 문의", close: "채팅 닫기", online: "고객 지원", demo: "프런트엔드 데모", demoNotice: "프런트엔드 데모 메시지는 이 브라우저에만 저장됩니다.",
  greeting: "무엇을 도와드릴까요?", greetingBody: "메시지나 스크린샷을 보내 주세요. 나중에 돌아와도 대화를 확인할 수 있습니다.", placeholder: "메시지 입력…", send: "메시지 보내기", attach: "이미지 첨부", removeImage: "이미지 제거", imageHint: "PNG, JPEG 또는 WebP · 최대 2 MB", imageInvalid: "2 MB 이하의 PNG, JPEG 또는 WebP 이미지를 선택하세요.", imageLoading: "이미지 준비 중…", imageAlt: "첨부 이미지", you: "나", agent: "상담원", sent: "전송됨", newMessages: "새 메시지", emptyMessage: "메시지를 입력하거나 이미지를 첨부하세요.", textTooLong: "메시지는 4,000자 이내로 작성하세요.", saveFailed: "저장하지 못했습니다. 작성 중인 내용은 유지됩니다. 다시 시도하세요.", storageFull: "데모 저장 공간이 가득 찼습니다. 이미지를 제거하거나 새 사용자 미리보기를 시작하세요.", sessionEnded: "이 데모 세션이 종료되었습니다. 다시 입장하세요.", frameBlocked: "이 페이지를 직접 열어 고객 지원 데모를 이용하세요.", unavailable: "브라우저 저장소를 사용할 수 없습니다. 활성화한 후 페이지를 새로고침하세요.", jsRequired: "고객 지원을 이용하려면 JavaScript를 활성화하세요.",
  desk: "상담 데스크", loginHeading: "상담원 로그인", loginTitle: "모든 고객 대화를 한곳에서.", loginBody: "대화와 고객 정보를 확인하고 문제 해결을 도와주세요.", loginNotice: "로컬 프런트엔드 미리보기입니다. 표시 이름과 이메일을 입력하면 체험할 수 있습니다. 실제 계정 인증은 하지 않습니다.", name: "표시 이름", email: "이메일", enter: "고객 지원 데모 입장", backToSite: "Fells로 돌아가기", logout: "고객 지원 데모 종료", inbox: "받은 편지함", all: "모든 대화", openFilter: "진행 중", resolvedFilter: "해결됨", unreadFilter: "읽지 않음", search: "고객 또는 메시지 검색", conversations: "대화", customers: "고객", waiting: "답장 대기", emptyInbox: "상담 준비가 완료되었습니다", emptyInboxBody: "사용자 미리보기에서 보낸 메시지가 여기에 표시됩니다. 예시 대화를 불러와 상담 데스크를 체험할 수도 있습니다.", seed: "예시 대화 불러오기", noResults: "일치하는 대화가 없습니다", selectConversation: "대화를 선택하세요", selectBody: "대화와 고객 정보를 확인하고 여기에서 답장하세요.", details: "고객 정보", back: "받은 편지함으로 돌아가기", customerId: "사용자 ID", joined: "가입일", workspaces: "워크스페이스", credits: "데모 크레딧", language: "언어", status: "대화 상태", resolve: "해결됨으로 표시", reopen: "대화 다시 열기", resolved: "해결됨", openStatus: "진행 중", sample: "예시 고객", previewUser: "미리보기 고객", messageCount: "개 메시지", noMessages: "아직 메시지가 없습니다", resolvedNotice: "이 대화는 해결되었습니다. 메시지를 보내면 다시 열립니다.", deskHint: "로컬 미리보기 · 이 브라우저의 탭 사이에서 답장 동기화", privacy: "이 데모에는 예시 정보를 사용하세요.", loading: "대화 불러오는 중…",
};
const es: SupportCopy = {
  availabilityOnline: "Agentes conectados", availabilityOffline: "Sin agentes · Deja un mensaje", availabilityUnknown: "Comprobando disponibilidad…", read: "Leído", unread: "Sin leer", agentTyping: "El agente está escribiendo…", userTyping: "El cliente está escribiendo…",
  latest: "Ir a los últimos mensajes", resetSearch: "Ver todas las conversaciones", sending: "Enviando…", userKeys: "Enter para enviar · Shift + Enter para una nueva línea", agentKeys: "Ctrl / ⌘ + Enter para enviar · Enter para una nueva línea", characterCount: "{count} / {limit} caracteres",
  title: "Atención al cliente", subtitle: "Un poco de ayuda, aquí mismo.", open: "Contactar con soporte", close: "Cerrar chat", online: "Atención al cliente", demo: "Demo de frontend", demoNotice: "Los mensajes de esta demo del frontend se guardan solo en este navegador.",
  greeting: "¿En qué podemos ayudarte?", greetingBody: "Envíanos un mensaje o una captura de pantalla. Tu conversación seguirá aquí cuando vuelvas.", placeholder: "Escribe un mensaje…", send: "Enviar mensaje", attach: "Adjuntar imagen", removeImage: "Quitar imagen", imageHint: "PNG, JPEG o WebP · hasta 2 MB", imageInvalid: "Elige una imagen PNG, JPEG o WebP de hasta 2 MB.", imageLoading: "Preparando imagen…", imageAlt: "Imagen adjunta", you: "Tú", agent: "Soporte", sent: "Enviado", newMessages: "Mensajes nuevos", emptyMessage: "Escribe un mensaje o adjunta una imagen.", textTooLong: "El mensaje puede tener hasta 4.000 caracteres.", saveFailed: "No se pudo guardar. Tu borrador sigue aquí; vuelve a intentarlo.", storageFull: "El almacenamiento de la demo está lleno. Quita una imagen o inicia una nueva vista previa de usuario.", sessionEnded: "Esta sesión de demo ha terminado. Vuelve a entrar.", frameBlocked: "Abre esta página directamente para usar la demo de soporte.", unavailable: "El almacenamiento del navegador no está disponible. Actívalo y recarga la página.", jsRequired: "Activa JavaScript para usar el soporte.",
  desk: "Panel de soporte", loginHeading: "Acceso del personal de soporte", loginTitle: "Todas tus conversaciones en un solo lugar.", loginBody: "Consulta conversaciones, conoce a tus clientes y ayúdales a avanzar.", loginNotice: "Vista previa local del frontend. Introduce un nombre visible y un correo para explorar; no se autentica ninguna cuenta.", name: "Nombre visible", email: "Correo electrónico", enter: "Entrar en la demo de soporte", backToSite: "Volver a Fells", logout: "Salir de la demo de soporte", inbox: "Bandeja de entrada", all: "Todas las conversaciones", openFilter: "Abiertas", resolvedFilter: "Resueltas", unreadFilter: "Sin leer", search: "Buscar clientes o mensajes", conversations: "Conversaciones", customers: "Clientes", waiting: "Pendientes de respuesta", emptyInbox: "Tu bandeja está lista", emptyInboxBody: "Los mensajes de la vista previa de usuario aparecerán aquí. También puedes cargar conversaciones de ejemplo para explorar el panel.", seed: "Cargar conversaciones de ejemplo", noResults: "No hay conversaciones que coincidan", selectConversation: "Elige una conversación", selectBody: "Lee la conversación y los datos del cliente y responde desde aquí.", details: "Datos del cliente", back: "Volver a la bandeja", customerId: "ID de usuario", joined: "Fecha de registro", workspaces: "Espacios de trabajo", credits: "Créditos de demo", language: "Idioma", status: "Estado de la conversación", resolve: "Marcar como resuelta", reopen: "Reabrir conversación", resolved: "Resuelta", openStatus: "Abierta", sample: "Cliente de ejemplo", previewUser: "Cliente de vista previa", messageCount: "mensajes", noMessages: "Todavía no hay mensajes", resolvedNotice: "Esta conversación está resuelta. Si envías un mensaje, se volverá a abrir.", deskHint: "Vista previa local · las respuestas se sincronizan entre pestañas de este navegador", privacy: "Usa datos de ejemplo en esta demo.", loading: "Cargando conversaciones…",
};
export function supportCopy(lang: string): SupportCopy {
  if (lang === "zh-CN" || lang === "zh") return zh;
  if (lang === "zh-TW" || lang === "zh-hant") return zhHant;
  if (lang === "ja") return ja;
  if (lang === "ko") return ko;
  if (lang === "es") return es;
  return en;
}
